### ISSUE TITLE
Query not applied to initial page load

### ISSUE THREAD

**Issue by suryagaddipati** [PolymerElements/iron-media-query#15] opened 2015-07-01 17:09 UTC
``!queryMatches`` is not triggered with initial page load .

https://elements.polymer-project.org/elements/iron-media-query?view=demo:demo/index.html 

this page text is empty if you load it on iphone emulator for example.

Not sure if this is expected behavior. 

The workaround is to use two matchers without the ``!queryMatches``

**Comment by Jsvcycling** [comment] 2015-07-01 18:09
I'm having this same problem. Can you post some sample code as to how to got around it? I can't seem to find a working workaround.

**Comment by Jsvcycling** [comment] 2015-07-01 18:15
Nevermind, I misread your workaround and didn't understand it at first.

For future reference, here's how @suryagaddipati's workaround looks like in code:

````
<template is="dom-bind">
    <iron-media-query query="(max-width: 768px)" query-matches="{{smallScreen}}"></iron-media-query>
    <iron-media-query query="(min-width: 768px)" query-matches="{{regularScreen}}"></iron-media-query>

    <template is="dom-if" if="{{smallScreen}}">
        <p>This is a small screen.</p>
    </template>

    <template is="dom-if" if="{{regularScreen}}">
        <p>This is a regular screen.</p>
    </template>
</template>
````

**Comment by vorotech** [comment] 2015-07-21 21:41
Another workaround that worked for me is to set default `false` value on the `app` object.
````js
app.smallScreen = false;
````
`iron-media-query` will override property if media width matchs the query specified and your bindings will work correctly in both cases.

**Comment by Sinjins** [comment] 2015-09-22 21:24
+1   Running into the same problem.  When you say "set default false on app object" @vorotech , do you mean set the databound property (smallScreen in this example) in the element's 'ready' event using js?  What if this isn't at the 'app' level per say, but rather the iron-media-query handling is done within a nested polymer element?  I've also tried setting a default value of false in the element's property declaration as follows, to no avail:  `_smallScreen: {type: Boolean, value: false}`

**Comment by Sinjins** [comment] 2015-09-23 19:54
This is causing me all sorts of issues.  Any suggestions....@notwaldorf possibly?

**Comment by blasten** [comment] 2015-09-25 22:33
This sounds like a timing issue; however I couldn't repro the issue. tested in chrome, mobile safari, safari, firefox. Maybe we fixed this issue in Polymer a long time ago? Could you guys send a code that reproduces the issue?

**Comment by Sinjins** [comment] 2015-09-26 19:34
@blasten I've been busy trying to get you a jsbin demonstrating replication of this issue.  Initially, I was having some trouble doing so.  I think I might be on the right track now though, and it appears it could have something to do with having the hidden$={{smallScreen}} applied on a tag inside an iron-list templated item.  If I remove the iron-list, the issue goes away.  I'll continue down this rabbit hole to get you a jsbin or determine root cause, but wanted to let you know in the meantime, in case something came to mind or you could suggest what might be causing the problem.

**Comment by Sinjins** [comment] 2015-09-26 23:29
Ok, here is the reproduction of the issue in jsbin:  http://jsbin.com/vapopa/1/edit?html,output
The problem seems to raise its ugly head when utilizing iron-ajax call to return array of items that are then used to bind to iron-list items.  In this scenario, trying to use iron-media-query to show or hide tags within the list item template doesn't work on the initial page load / iron-list items binding time.  It will respond once the page is loaded though (i.e. if you scale viewport size after the page has loaded things will disappear/appear appropriately).  Its just the first page view that is shown on the initial page load/iron-list items binding that is the issue.  This certainly causes a problem in mobile, especially.

**Comment by blasten** [comment] 2015-09-27 23:55
@sjmiles This issue is confirmed, but I'm moving it to https://github.com/PolymerElements/iron-list/issues/107.   Feel free to reopen this issue if you have a repro code using iron-media-query only.

**Closed by blasten** 2015-09-27 23:55 UTC
Labels: code-yellow, pending-response
